### ISSUE TITLE
Should not hardcode dev uniresolver URL

### ISSUE THREAD

**Issue by SamHellawell** [0xPolygonID/js-sdk#101]
**Describe the bug**
In the constants file there is a line: https://github.com/0xPolygonID/js-sdk/blob/main/src/iden3comm/constants.ts#L47C1-L48C1

```
export const UNIVERSAL_RESOLVER_URL = 'https://dev.uniresolver.io/1.0/identifiers';
````

This is a dev instance and doesnt have guarnteed uptime, which may cause polygonid did resolution to fail with this SDK. You shouldn't be hardcoding it here and pointing everyone's usage to it. Check the uni resolver site for more info about the dev intsance.

**Expected behavior**
Configuration value or a native way of resolving DIDs

**Comment by vmidyllic** [comment]
@SamHellawell thank you for the feedback. 
we are aware of the dev instance's non-stability and will remove it as a default resolver. The functionality of JWS unpacker is beta. If your flow now is dependent on the resolver I suggest using your custom. e.g. running a universal resolver instance, etc.

**Comment by SamHellawell** [comment]
Hi there,

We are running a custom uniresolver instance but unfortunately cannot point the JS SDK to it due to the hardcoded variable! Would a quick update to perhaps read from ENV variables work and fallback if not there?

Such as:

```
export const UNIVERSAL_RESOLVER_URL = process.env.UNIVERSAL_RESOLVER_URL || 'https://dev.uniresolver.io/1.0/identifiers';
```

(might need some wrapping to make it work for web builds)

Right now we can skip the JWS verification etc that may need DID resolution, but better to be able to restore it soon for the auth flows.

Thanks

**Comment by vmidyllic** [comment]
@SamHellawell 

You should be able to pass custom resolver through parameter to JWS packer 
https://github.com/0xPolygonID/js-sdk/blob/203082425e5de6450266d53e6aca562a66fff66b/src/iden3comm/packers/jws.ts#L39

e.g.

``` javascript
    resolveDIDDocument = {
      resolve: () => Promise.resolve({ didDocument: didExample } as DIDResolutionResult)
    };

    const kmsProvider = new Sec256k1Provider(KmsKeyType.Secp256k1, memoryKeyStore);

    kms = new KMS();

    kms.registerKeyProvider(kmsProvider.keyType, kmsProvider);

    packer = new JWSPacker(kms, resolveDIDDocument);
```
