### ISSUE TITLE
Is support of $gte and $lte planned?

### ISSUE THREAD

**Issue by joelamouche** [0xPolygonID/js-sdk#147]
**This is more a feature request...**

https://github.com/0xPolygonID/js-sdk/blob/main/src/circuits/comparer.ts

I am seeing that gte and lte operators are not supported yet. Is this planned for the future?

**Comment by vmidyllic** [comment]
@joelamouche  LTE / GTE operation will be supported in the new circuit, as well in the js sdk.  The release and trusted setup of the new circuit is planned for the end of Q4. As well as some important features such as Sybil resistance, linked and joined proofs..

**Comment by vmidyllic** [comment]
LTE / GTE  is supported in v3 beta.1 circuit
