### ISSUE TITLE
Error: can't fetch revocation status

### ISSUE THREAD

**Issue by bhagat-harshil** [0xPolygonID/js-sdk#153]
While issuing a credential via SDK, I am facing this error : "Error: can't fetch revocation status"
Below is the function for creating identity:
`  const { did: issuerDID, credential: issuerAuthBJJCredential } =
    await identityWallet.createIdentity({
      method: core.DidMethod.Iden3,
      blockchain: core.Blockchain.Polygon,
      networkId: core.NetworkId.Mumbai,
      revocationOpts: {
        type: CredentialStatusType.Iden3ReverseSparseMerkleTreeProof,
        id: 'https://rhs-staging.polygonid.me'
      }
    });`

Here is the issuerAuthBJJCredential credentials of the issuer which will issue the credentials to user
`W3CCredential {
  id: 'urn:0ac440df-ef01-47c3-8923-fbab84369cbd',
  '@context': [
    'https://www.w3.org/2018/credentials/v1',
    'https://schema.iden3.io/core/jsonld/iden3proofs.jsonld',
    'https://schema.iden3.io/core/jsonld/auth.jsonld'
  ],
  type: [ 'VerifiableCredential', 'AuthBJJCredential' ],
  credentialSubject: {
    x: '5484876829365717676736908371782461918096221954585422816383236586450076389851',
    y: '91800604486763415508230927229839682844173663116373059195732276742646075462',
    type: 'AuthBJJCredential'
  },
  issuer: 'did:iden3:polygon:mumbai:x1gbYoAgnpCYcyUyb7YonDW93fLntN9xEjBSDUYGw',
  expirationDate: undefined,
  issuanceDate: '2023-11-15T11:06:12.323Z',
  credentialSchema: {
    id: 'https://schema.iden3.io/core/json/auth.json',
    type: 'JsonSchema2023'
  },
  credentialStatus: {
    id: 'https://rhs-staging.polygonid.me/node?state=7202b50c648bfa6da95fefda16d748bbb4809e6590dfbefa96be770bf5c2f404',
    type: 'Iden3ReverseSparseMerkleTreeProof',
    revocationNonce: 0
  },
  proof: [
    Iden3SparseMerkleTreeProof {
      coreClaim: [Claim],
      issuerData: [Object],
      type: 'Iden3SparseMerkleTreeProof',
      mtp: [Proof]
    }
  ]
}`

But I am unable to issue credentials and facing the below error:
`const credential = await identityWallet.issueCredential(issuerDID, credentialRequest);`

`Error: can't fetch revocation status
    at RHSResolver.resolve (/home/harshil/didJsSdk/js-sdk-examples/node_modules/@0xpolygonid/js-sdk/src/credentials/status/reverse-sparse-merkle-tree.ts:130:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async CredentialWallet.getAuthBJJCredential (/home/harshil/didJsSdk/js-sdk-examples/node_modules/@0xpolygonid/js-sdk/src/credentials/credential-wallet.ts:251:32)
    at async IdentityWallet.issueCredential (/home/harshil/didJsSdk/js-sdk-examples/node_modules/@0xpolygonid/js-sdk/src/identity/identity-wallet.ts:671:37)
    at async issueCredential (/home/harshil/didJsSdk/js-sdk-examples/index2.ts:186:22)`

I was using polygon's RHS server : 'https://rhs-staging.polygonid.me' and i also tried running up my own RHS server but got the same issue

After noticing the issuerAuthBJJCredential credentials, i got to know that the `'https://rhs-staging.polygonid.me/node?state=7202b50c648bfa6da95fefda16d748bbb4809e6590dfbefa96be770bf5c2f404`' url is invalid, there is no api implemented in iden3's rhs server to fetch status like this. According to their docs, the effective URL should be `https://rhs-staging.polygonid.me/node/7202b50c648bfa6da95fefda16d748bbb4809e6590dfbefa96be770bf5c2f404`
But still i am not sure if this is the reason for the revocation error, help me out here if i am doing something wrong.
`

**Comment by vmidyllic** [comment]
url  `https://rhs-staging.polygonid.me/node?state=7202b50c648bfa6da95fefda16d748bbb4809e6590dfbefa96be770bf5c2f404` is tranforming inside js-sdk according to the algorithm and fetches the node information from url
 `https://rhs-staging.polygonid.me/node/7202b50c648bfa6da95fefda16d748bbb4809e6590dfbefa96be770bf5c2f404`
 
 Probably you didn't setup a contract address, so latest state of the issuer can't be fetched from blockchain.
 Can you check that you inited the storage with a right state contract address?

**Comment by bhagat-harshil** [comment]
Thanks @vmidyllic for the help, there was some mismatch between my RPC urls and RHS server but it is working now.
Another issue I am facing further while verifying the proof generated using `AtomicQueryMTPV2` Circuit.

`await proofService.verifyProof({ proof, pub_signals }, CircuitId.AtomicQueryMTPV2)`

The above code is returning me this Error:
`/home/harshil/didJsSdk/js-sdk-examples/node_modules/@0xpolygonid/js-sdk/dist/node/cjs/proof/witness_calculator.js:148
            throw new Error(`Not all inputs have been set. Only ${input_counter} out of ${this.instance.exports.getInputSize()}`);
                  ^
Error: Not all inputs have been set. Only 167 out of 211
    at WitnessCalculator._doCalculateWitness (/home/harshil/didJsSdk/js-sdk-examples/node_modules/@0xpolygonid/js-sdk/dist/node/cjs/proof/witness_calculator.js:148:19)
    at WitnessCalculator.calculateWTNSBin (/home/harshil/didJsSdk/js-sdk-examples/node_modules/@0xpolygonid/js-sdk/dist/node/cjs/proof/witness_calculator.js:180:20)
    at NativeProver.generate (/home/harshil/didJsSdk/js-sdk-examples/node_modules/@0xpolygonid/js-sdk/dist/node/cjs/proof/prover.js:60:51)
    at async ProofService.generateProof (/home/harshil/didJsSdk/js-sdk-examples/node_modules/@0xpolygonid/js-sdk/dist/node/cjs/proof/proof-service.js:64:40)
    at async issueCredential (/home/harshil/didJsSdk/js-sdk-examples/index2.ts:241:34)`

I have succesfully generated the Proofs via `const { proof, pub_signals } = await proofService.generateProof(proofReqMTP, userDID);` and below is my MTP request
`const proofReqMtp: ZeroKnowledgeProofRequest = {
    id: 1,
    circuitId: CircuitId.AtomicQueryMTPV2, // or AtomicQueryMTPV2onChain
    optional: false,
    query: {
      allowedIssuers: ['*'],
      type: credentialRequest.type,
      context:
        'https://raw.githubusercontent.com/iden3/claim-schema-vocab/main/schemas/json-ld/kyc-v3.json-ld',
      credentialSubject: {
        documentType: {
          $eq: 99
        }
      }
    }`
  };

is there any step I am missing here?
