### ISSUE TITLE
v3 proof generation fails

### ISSUE THREAD

**Issue by sirpy** [0xPolygonID/js-sdk#186]
@vmidyllic @Kolezhniuk 
This issue should be re-opened.
the js-sdk already uses generateProof the only contract-request does differently is passing the challenge correctly.
In my tests i've already fixed the challenge passing, once you pass the challenge correctly then there's the circuit bug i've reported.
If you pass challenge correctly then a proof is generated correctly for V2 requests such as `AtomicQueryMTPV2OnChain`
But throws the error i've reported if you request `AtomicQueryV3OnChain`

_Originally posted by @sirpy in https://github.com/0xPolygonID/js-sdk/issues/182#issuecomment-1964860213_

**Comment by vmidyllic** [comment]
Handle authorization requests now works only with off-chain circuits. And challenge is not required for them.
 As I understood you use case you need to generate proof for AtomicQueryMTPV2OnChain, but do not need to send onchain, right? 
 
 That is why you need a challenge.  We will reconsider the possibility to pass challenge as parameter to handleAuthorizationRequest function, but for now you should use generate proof function. And contruct response manually. 
 
 
 We reproduced an issue with witness generation for v3 onchain, will fix asap.
