### ISSUE TITLE
v3 input generator doesn't calculate nullifier value

### ISSUE THREAD

**Issue by sirpy** [0xPolygonID/js-sdk#189]
**Describe the bug**
1. A nullifier should be calculated in case of a nullifierSessionID but it is always 0 on public inputs
2. typo some nullifierSessionID are written nullifierSessionId (last d isn't capitalized)

**To Reproduce**
generate a proof for CircuitId.AtomicQueryV3OnChain with nullifierSessionID
look at slot 5 of public inputs = 0

**Expected behavior**
slot 5 of public inputs not 0 and equal to the calculation specified here
https://devs.polygonid.com/docs/verifier/query-builder/#proof-of-uniqueness

**Comment by OBrezhniev** [comment]
Hello!

If any of the following inputs is 0:
- credProfileNonce
- verifierID
- nullifierSessionID

output would be 0 too.

**Comment by sirpy** [comment]
@OBrezhniev
I don't understand, there simply isnt calculation of nullifier in the sdk code. not related to the inputs.
why credProfileNonce can't be 0? if it is the genesis id.

**Comment by OBrezhniev** [comment]
If there wouldn't be non-zero credProfileNonce, it would be possible for some identities (which have done state transition or otherwise known to attacker) to brute-force their genesisId from the nullifier, because all other inputs to hash function would be publicly available. That's why we decided to disallow zero value here - to protect from possible deanonymization.

**Comment by OBrezhniev** [comment]
To protect privacy regular users should refrain from using genesisId in interactions with others. Only issuers must use genesisId to issue credentials, because otherwise it would be impossible to verify these credentials.

**Comment by sirpy** [comment]
@OBrezhniev
nullifier works with profiles but:
The docs says that the nullifier is supposed to be unique across profiles
1. I tried to generate the same proof with two profiles and got two different nullifiers
2. how can it be unique if the profile nonce is included in the hash?

**Comment by OBrezhniev** [comment]
I don't know how you generate nullifiers. If you are manually generating it (and not the Polygon ID wallet), then maybe you are providing wrong inputs. Circuit should generate the same nullifier for different profiles used to authenticate to verifier, and it depends on the credential to be issued only once by the issuer to only one of user's profiles (this is the one, nonce of which is used to calculate the nullifier).

**Comment by sirpy** [comment]
@OBrezhniev when you say issue credential only once, what fields in the credential are used for determining the uniqueness of the credential? ie to generate a unique nullifier?

**Comment by OBrezhniev** [comment]
> @OBrezhniev when you say issue credential only once, what fields in the credential are used for determining the uniqueness of the credential? ie to generate a unique nullifier?

Nullifier value doesn't depend on data inside a credential. It's a job of issuer to control somehow that one natural person receives only one credential of a specific type and to only one identitier. How issuer is doing this is out of protocol control.

Technically it could be multiple credentials of the same type to the same identifier (e.g. during credential refresh process user may end up with multiple valid credentials) and it would still give the same nullifier.

Another example is "Passport Credential", where issuer may issue two passport credentials to the user, when user has two valid physical passports, e.g. one is about to expire but still valid, and new one. Or from different countries.
If issuer detects it and allows to issue both credentials only to the same identifier, then nullifier would have the same value for both passports.

> @OBrezhniev I think it would have made sense if you could use only one credential with a specific schema from a specific issuer. What's the use case to allow multiple credentials from same issuer with same schemahash?

See above.

**Comment by sirpy** [comment]
ok I see so the nullifier is unique based on schemahash+profileNonce
so as long as the same credential type is issued to the same profile it will generate the same nullifier.
credential issuer needs to handle not issuing same credential to different profiles if it is the same person
