### ISSUE TITLE
challenge needs to be reversed

### ISSUE THREAD

**Issue by sirpy** [0xPolygonID/js-sdk#190]
**Describe the bug**
The on-chain contracts use iden3 utils to convert the challenge int256 to address
Iden3 utils for some reason reverse the bytes so challenge doesnt match sender

**To Reproduce**
Try to verify on-chain and put challenge=msg.sender

**Expected behavior**
The on-chain contracts do not reverse the address or when preparing the inputs challenge should be reversed.
Preferably the on-chain contracts should be fixed

**Comment by vmidyllic** [comment]
it is expected to be swapped before the contract invoked handler is executed:

see example:[link]( https://github.com/0xPolygonID/js-sdk/blob/f6355df9545c294c3b140cb4605e8db508074d42/tests/handlers/contract-request.test.ts#L581)

The reason for that is the next circuit accepts big integer which has a maximum finite value (restriction from the BJJ curve) .
To support more value swap procedure is required for bytes that are set to int. ( all integers are supposed to be in little-endian).

We accept the challenge as bigint - so we won't manipulate it and pass to sign whatever user provided.
But your concern is valid. We will think how to doublecheck that challenge is corresponding to the sender address on js-sdk level
