### ISSUE TITLE
Request: is there a way to generate a credential without subject id?

### ISSUE THREAD

**Issue by marsouin** [0xPolygonID/js-sdk#242]
**Describe the bug**

The issuer node allows for link generation where the subject is unknown at the time the credential is created. Is there a way to implement this use case with the JS SDK? Can we put something other than the subject DID in the `credentialSubject`? 
In our implementation, we do not necessarily have access to the issuer private key at the time the user clicks on the link to issue the credential, but there's no way to pre-sign the credential if we do not know the subject DID, right?
Thank you!

**Comment by marsouin** [comment]
Ok thank you, very clear. Is that how links are created and used in the issuer node?

**Comment by vmidyllic** [comment]
By following the flow  I would say yes.
