### ISSUE TITLE
Missing Display Method Attribute in Credential Request During Generation

### ISSUE THREAD

**Issue by Sshovon** [0xPolygonID/js-sdk#261]
**Objective: Add display method in during credential issuance/offer creation**

Issuance flow:
- Firstly, creating credential but [credentialRequest](https://github.com/0xPolygonID/js-sdk/blob/1e72293ef186fbb4f9a2cdc1d92ddb03d993a451/src/credentials/models.ts#L24) object has no option to pass the display method. But the response credential is [W3Credential](https://github.com/0xPolygonID/js-sdk/blob/1e72293ef186fbb4f9a2cdc1d92ddb03d993a451/src/verifiable/credential.ts#L41) instance, which can technically contain a displayMethod.
```
const credential = await identityWallet.issueCredential(issuerDid, credentialRequest);
```
- So I am manually setting the displayMethod value before releasing the credential to the holder. Display metadata url is similar to the [link](https://maroon-additional-grouse-745.mypinata.cloud/ipfs/QmeFoC7D6RNcR5qWGFJGALWeeqSNEfkfeWxXdizNGi2oyb).
```
credential.displayMethod = {
               id: schema.displayMetadataUrl,
               type: "Iden3BasicDisplayMethodV1"
           }
```
- This shows the credential display perfectly in the polygonId wallet.
![image](https://github.com/user-attachments/assets/011194e9-0247-4028-8e22-52637ce8b6df)

- But the problem occurs  when I try to give a presentation using that credential. And I get the following error. I am also adding the stack trace. I am using js-sdk:1.17.2 .
![image](https://github.com/user-attachments/assets/8f79fd8b-8230-4aba-9551-c329414d96f8)
- Without credential display the proof presentation works perfectly.
-  I can add the stack trace if you want to examine that.
- It would be great if you add an option to pass the display method in **credentialRequest**.

** Environment info :**
 - OS version: Ubuntu 22.04 lts
 - Node version:  20.11
 - Package version: Js-sdk 1.17.2
 -  Wallet: PolygonId wallet

The whole process is added in the doc with stack trace.
https://docs.google.com/document/d/1qrG_dG_mQon0n73IWe0o-3tU2-e8waGgpoKnpQvUtgg/edit?usp=sharing

**Comment by vmidyllic** [comment]
When you add smth manually to credential after the proof has been generated (signature or mtp) and user fetches this credential proof generation won't work because merkle root of credential has been changed and doesn't correspond to the one which is signed or included to the issuer's tree.

So this is an not an issue in sdk, but rather the enhancement to support display method.

**Comment by Sshovon** [comment]
Thanks for the response. Yes, I was also thinking the same that the proof aren't same if I inject manually after the credential is already created. It would be really great if this is added in the 
 But I am a bit confused about this part  `Also you didn't add context for display type in case your idea was to regenerate a proof.` Where do I need to add this  context for display type, in schemas ?

**Comment by vmidyllic** [comment]
According to the jsonld standard there should be a context definition for a field displayMethod. [Docs](https://iden3-communication.io/w3c/display-method/overview/)

**Comment by Sshovon** [comment]
I totally missed that context part... Thanks a lot @vmidyllic .
Is there any expected release time for this support ?

**Comment by vmidyllic** [comment]
added in [1.18.2](https://github.com/0xPolygonID/js-sdk/releases/tag/v1.18.2)

**Comment by Sshovon** [comment]
Hey @vmidyllic , the display metadata is working with the wallet. Proof request is also working on polygonId wallet. 
But I found something interesting. 
When the context is being generated after the credential is created, it is getting following value.
```
[
  'https://schema.iden3.io/core/jsonld/displayMethod.jsonld',
  'https://www.w3.org/2018/credentials/v1',
  'https://schema.iden3.io/core/jsonld/iden3proofs.jsonld',
  'https://maroon-additional-grouse-745.mypinata.cloud/ipfs/QmVbAQavws5bVPCuYfApx3DjSSAEsNYivhhpUTm4rUxkzT'
]
```
But according to the specification of [verifiable data model v1](https://www.w3.org/TR/vc-data-model/#contexts) `https://www.w3.org/2018/credentials/v1`  should always be the first element . 
Also, if I provide extra context in the context attribute of credentialRequest it being appended as first element.
