### ISSUE TITLE
chainId "xxxx" not supported

### ISSUE THREAD

**Issue by Sshovon** [0xPolygonID/js-sdk#287]
I am trying to run [handleAuthRequest](https://github.com/0xPolygonID/js-sdk-examples/blob/6fdb122a7a58dcce54f67b2a8572266ec4c835eb/index.ts#L429) function but getting following error. 
```
Error: chainId "80002" not supported
    at EthStateStorage.networkByChainId (/home/frcs/my-zone/privado/js-sdk-examples/node_modules/@0xpolygonid/js-sdk/dist/node/cjs/storage/blockchain/state.js:192:19)
    at EthStateStorage.getStateContractAndProviderForId (/home/frcs/my-zone/privado/js-sdk-examples/node_modules/@0xpolygonid/js-sdk/dist/node/cjs/storage/blockchain/state.js:182:29)
    at EthStateStorage.publishState (/home/frcs/my-zone/privado/js-sdk-examples/node_modules/@0xpolygonid/js-sdk/dist/node/cjs/storage/blockchain/state.js:81:50)
    at IdentityWallet.transitState (/home/frcs/my-zone/privado/js-sdk-examples/node_modules/@0xpolygonid/js-sdk/dist/node/cjs/identity/identity-wallet.js:671:47)
    at async handleAuthRequest (/home/frcs/my-zone/privado/js-sdk-examples/index.ts:482:16)
    at async main (/home/frcs/my-zone/privado/js-sdk-examples/index.ts:1065:7)
    at async /home/frcs/my-zone/privado/js-sdk-examples/index.ts:1078:3

```
I am using the `defaultEthConnectionConfig` from `js-sdk` with my rpc.  And the contract address is `0x1a4cC30f2aA0377b0c3bc9848766D90cb4404124`. 
It seems `defaultEthConnectionConfig` doesn't contain chainId.  So it's throwing error from  [this](https://github.com/0xPolygonID/js-sdk/blob/51087949a6727164a2d6cca1595e39126ac0effa/src/storage/blockchain/state.ts#L254) 
The config array looks like this
```
config [
  {
    url: my_rpc_url,
    defaultGasLimit: 600000,
    minGasPrice: '0',
    maxGasPrice: '100000000000',
    confirmationBlockCount: 5,
    confirmationTimeout: 600000,
    contractAddress: '0x1a4cC30f2aA0377b0c3bc9848766D90cb4404124',
    receiptTimeout: 600000,
    rpcResponseTimeout: 5000,
    waitReceiptCycleTime: 30000,
    waitBlockCycleTime: 3000
  }
]
```
And if i comment out the find and return the object from the array directly it works.

My did was created using,
```
method: core.DidMethod.PolygonId,
  blockchain: core.Blockchain.Polygon,
  networkId: core.NetworkId.Amoy,
```
It also throws error if I create did using privado mainnet. 

Am I missing out something? Is there any issue on my setup ? 

**To Reproduce**
I have tried `js-sdk@1.21.3`  and `js-sdk@1.18.3`, and same thing happened.
Though if I use `js-sdk@1.10.3` the whole thing works without any issue.

** Environment info **
 - OS version : Ubuntu 22.04
 - Node version: 20.11
 - Package version : js-sdk@1.21.3

**Comment by Sshovon** [comment]
dependencies for js-sdk
```
"peerDependencies": {
    "@0xpolygonid/js-sdk": "1.21.3",
    "@0xpolygonid/mongo-storage": "github:0xPolygonID/nodejs-storage-example",
    "@iden3/js-crypto": "1.1.0",
    "@iden3/js-jsonld-merklization": "1.4.1",
    "@iden3/js-jwz": "1.8.0",
    "@iden3/js-merkletree": "1.3.1"
  },
  "dependencies": {
    "dotenv": "^16.3.1",
    "ethers": "~6.13.1",
    "mongodb-memory-server": "^8.16.0",
    "mongodb": "^6.1.0"
  },
```

**Comment by Sshovon** [comment]
So If I manually put the chainId.. it works..
Do I need to maintain the chainId thing for all the  configs that I use ?
Closing the issue as this is not a bug.

**Comment by Kolezhniuk** [comment]
Hello @Sshovon, 
Do I need to maintain the chainId thing for all the configs that I use ? - Yes, at least at that momment
We will review this interface in the future https://github.com/0xPolygonID/js-sdk/blob/51087949a6727164a2d6cca1595e39126ac0effa/src/storage/blockchain/state.ts#L18 and to make chainId non optional field to avoid confusion
Thanks for rising this up
