### ISSUE TITLE
How to get tests working

### ISSUE THREAD

**Issue by tahpot** [0xPolygonID/js-sdk#49]
Running the unit tests show these errors:

`Error: getaddrinfo ENOTFOUND mytestwallet.com`

and

`Error: connect ECONNREFUSED 127.0.0.1:80`

Is there some extra configuration required?

**Comment by vladyslavmunin** [comment]
Have you setup env variables?

export WALLET_KEY="...key in hex format"
export RPC_URL="...url to polygon network rpc node"
export RHS_URL="..reverse hash service url"
