### ISSUE TITLE
JSONValue type is overly wide

### ISSUE THREAD

**Issue by nedgar** [0xPolygonID/js-sdk#52]
The [type definition of JSONValue](https://github.com/0xPolygonID/js-sdk/blob/main/src/iden3comm/types/index.ts#L14) allows `object` and `Array<object>` (in addition to string | number | boolean) which seems overly wide.

Should it instead be: `type JSONValue = string | number | boolean | JSONObject | Array<JSONObject>`?

**Comment by vmidyllic** [comment]
can you suggest what are you going to achieve with such a change? 
how does `object` work wrong for your use case? 
I guess `JSONValue = string | number | boolean | JSONObject` where JSONObject contains JSONValue properties can create a circular dep. 
We will have a detailed look on this problem.

**Comment by nedgar** [comment]
@vmidyllic I'm not hitting it as a real issue, since my examples using it are valid JSON, but type `object` allows values that aren't supported in JSON, e.g. functions.

With the current typing a function is allowed:

<img width="621" alt="image" src="https://user-images.githubusercontent.com/692834/230449480-ead2f7f8-2020-4ab5-bbc3-d3b03a4ce686.png">

With the type changed (corrected from my original comment) to `type JSONValue = string | number | boolean | JSONObject | Array<JSONValue>`, it flags the function as invalid:

<img width="697" alt="image" src="https://user-images.githubusercontent.com/692834/230449267-f5f289d5-f832-465d-8729-164c243ab639.png">

**Comment by vmidyllic** [comment]
@nedgar  we add this task to the backlog. But it's not first priority.

**Comment by nedgar** [comment]
No worries, it's not urgent at all, thanks.

**Comment by sanketsaagar** [comment]
Hi @nedgar , As our team has acknowledged that we have added this task to our backlog and it will be resolved, You may close the issue.
