### ISSUE TITLE
Convert string typed query value to hash

### ISSUE THREAD

**Issue by nedgar** [0xPolygonID/js-sdk#67]
From Slack discussion with @OBrezhniev (with minor wording clarifications):

I’m wondering about the status and plans for handling string values. e.g. say I have a passport credential with passport “number” which may contain both letters and numbers. The merkelization algorithm uses the Poseidon hash if the field has string type, but currently I need to know this when verifying a query — the value to compare against must be the hash, not the original string. However, the filter to select matching credentials in wallet doesn’t match. It seems like the query processing would need to check the field type in schema to handle this properly.

It didn’t work with the version of the SDK I have (1.0.0-beta.5). That is, it found a matching credential in credential wallet, but it then failed when trying to serialize the inputs since the string value couldn’t be converted to big int.

For now, in my “all-in-one” demo, I keep the string value in the query, use that to select matching credentials, then convert the value to hash before generating the proof. It would be good for the SDK to support this directly.

**Comment by sanketsaagar** [comment]
Hi @nedgar , definitely in the next release, we will clarify this and let you know. As it is an issue on mobile and maybe it is already resolved in Sdk but not in the app.

**Comment by nedgar** [comment]
This looks to have been fixed in #90 (for issue #89), but see Q's / concerns there.
